"""
Publish the ERP database to disk as a static read-only snapshot.

For each market in markets_config.MARKETS, dumps the latest computation +
full history to docs/data/{market}.json. Also emits docs/data/all.js (a
single-file bundle with `window.__ERP_SNAPSHOT__ = {...}` for the static
docs/index.html viewer to load via <script src> on file://) and
docs/data/index.json (small metadata index).

Phase 5b deliverable. Pairs with docs/index.html. Phase 5c will wire this
up to .github/workflows/snapshot.yml for nightly publication; for now run
manually:

    python scripts/publish_snapshot.py

Exit codes mirror main.py's --all-markets aggregate pattern:
  0 — at least one market published OK (others may have been skipped/failed)
  1 — every market failed (DB cold, schema mismatch, …)
"""
from __future__ import annotations

import json
import math
import sys
from datetime import datetime, timezone
from pathlib import Path

import numpy as np

# Resolve repo-root imports the same way seed_historical.py:28 does.
ROOT_DIR = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT_DIR))

import config  # noqa: F401  (loads .env into os.environ; harmless if absent)
from database import get_history, get_latest
from markets_config import MARKETS, get_market

DOCS_DATA_DIR = ROOT_DIR / "docs" / "data"
METHOD = "fcfe"


def _clean(o):
    """Strip NaN → None recursively; everything else passed through."""
    if isinstance(o, dict):
        return {k: _clean(v) for k, v in o.items()}
    if isinstance(o, list):
        return [_clean(v) for v in o]
    if isinstance(o, float) and math.isnan(o):
        return None
    return o


def _build_payload(code: str) -> dict | None:
    """Return the full per-market payload, or None if the DB has nothing for it."""
    spec = get_market(code)
    latest = get_latest(method=METHOD, market=code)
    if latest is None:
        return None

    df = get_history(method=METHOD, market=code)
    if df.empty:
        history = []
    else:
        df = df.copy()
        df["date"] = df["date"].astype(str)
        df = df.replace({np.nan: None})
        history = df.to_dict(orient="records")

    return {
        "market": code,
        "name": spec.name,
        "currency": spec.currency,
        "currency_symbol": spec.currency_symbol,
        "data_quality": spec.data_quality,
        "display_index_name": spec.display_index_name,
        "last_updated": datetime.now(timezone.utc).isoformat(timespec="seconds"),
        "latest": _clean(dict(latest)),
        "history": _clean(history),
    }


def _write_json(path: Path, obj) -> None:
    with path.open("w", encoding="utf-8") as fp:
        json.dump(obj, fp, indent=2, default=str, allow_nan=False)


def main() -> int:
    DOCS_DATA_DIR.mkdir(parents=True, exist_ok=True)

    payloads: dict[str, dict] = {}
    summary_rows: list[str] = []
    ok_count = 0
    skip_count = 0

    for code in MARKETS.keys():
        try:
            payload = _build_payload(code)
        except Exception as e:  # noqa: BLE001 — per-market isolation, mirror Phase 5a
            summary_rows.append(f"[fail] {code:<7} {type(e).__name__}: {e}")
            continue

        if payload is None:
            summary_rows.append(f"[skip] {code:<7} no rows in DB (run main.py --update --market {code})")
            skip_count += 1
            continue

        out_path = DOCS_DATA_DIR / f"{code}.json"
        _write_json(out_path, payload)
        payloads[code] = payload
        ok_count += 1

        latest = payload["latest"]
        erp_pct = latest.get("implied_erp")
        erp_str = f"{erp_pct * 100:.2f}%" if isinstance(erp_pct, (int, float)) else "n/a"
        summary_rows.append(
            f"[ ok ] {code:<7} {latest.get('date','?')} erp={erp_str:<7} (history={len(payload['history'])})"
        )

    # all.js bundle — script-tag-loadable on file://
    all_js_path = DOCS_DATA_DIR / "all.js"
    bundle_json = json.dumps(payloads, indent=2, default=str, allow_nan=False)
    all_js_path.write_text(
        "// Generated by scripts/publish_snapshot.py — do not edit by hand.\n"
        "// Loaded by docs/index.html via <script src> for file:// compatibility.\n"
        f"window.__ERP_SNAPSHOT__ = {bundle_json};\n",
        encoding="utf-8",
    )

    # index.json — small metadata index
    index_obj = {
        code: {
            "data_quality": p["data_quality"],
            "name": p["name"],
            "currency": p["currency"],
            "last_updated": p["last_updated"],
            "latest_date": p["latest"].get("date"),
            "latest_erp": p["latest"].get("implied_erp"),
            "history_count": len(p["history"]),
        }
        for code, p in payloads.items()
    }
    _write_json(DOCS_DATA_DIR / "index.json", index_obj)

    print("\n".join(summary_rows))
    print(
        f"\nWrote {ok_count} market(s), skipped {skip_count}, "
        f"to {DOCS_DATA_DIR.relative_to(ROOT_DIR)}/"
    )

    return 0 if ok_count > 0 else 1


if __name__ == "__main__":
    raise SystemExit(main())
